build:
    environment:
        php:
            version: '7.0'
    tests:
        override:
            -
                command: vendor/bin/simple-phpunit -c phpunit.coverage.xml.dist
                coverage:
                    file: tmp/logs/coverage.xml
                    format: clover

checks:
    php: true

filter:
    excluded_paths:
        - Tests/*
