build:
    environment:
        php:
            version: '7.0'
    tests:
        override:
            - vendor/bin/simple-phpunit

checks:
    php: true

filter:
    excluded_paths:
        - Tests/*
